# Generated by Django 5.2.2 on 2025-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug тега (для URL и CSS-классов)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название решения')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('organization', models.CharField(max_length=200, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, verbose_name='Сайт')),
                ('image', models.ImageField(blank=True, upload_to='itsolutions/%Y/%m/%d/', verbose_name='Изображение/логотип')),
                ('status', models.CharField(choices=[('startup', 'Стартап'), ('product', 'Продукт')], default='product', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tags', models.ManyToManyField(blank=True, related_name='solutions', to='catalog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'IT-решение',
                'verbose_name_plural': 'IT-решения',
                'ordering': ['-created_at'],
            },
        ),
    ]
