# Generated by Django 5.2.2 on 2025-06-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsolution',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='itsolution',
            name='status',
            field=models.CharField(choices=[('startup', 'Стартап'), ('product', 'Продукт')], db_index=True, default='product', max_length=20, verbose_name='Тип решения'),
        ),
        migrations.CreateModel(
            name='ITRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок запроса')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Контактное лицо (ФИО)')),
                ('company_name', models.CharField(max_length=200, verbose_name='Компания / ИП')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('moderation_status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tags', models.ManyToManyField(blank=True, related_name='requests', to='catalog.tag', verbose_name='Теги (тематики запроса)')),
            ],
            options={
                'verbose_name': 'Запрос на решение',
                'verbose_name_plural': 'Запросы на решения',
                'ordering': ['-created_at'],
            },
        ),
    ]
