# Generated by Django 5.2.2 on 2025-06-09 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('company', models.CharField(max_length=255, verbose_name='Компания / ИП')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('agreement', models.BooleanField(verbose_name='Согласие на обработку данных')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подачи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tag', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запрос на ИТ-решение',
                'verbose_name_plural': 'Запросы на ИТ-решения',
                'ordering': ['-created_at'],
            },
        ),
    ]
